name: CI

on:
  push:
    branches: [ main, develop, setup-ci]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install dependencies
      run: |
        chmod +x scripts/install_dependencies.sh
        ./scripts/install_dependencies.sh
    
    - name: Configure CMake
      run: cmake -B build -DCMAKE_BUILD_TYPE=Release
    
    - name: Build
      run: cmake --build build --config Release
    
    - name: Run tests
      run: |
        cd build
        ctest --output-on-failure --verbose